### ISSUE TITLE
Convenient way to pass multiple yml files to ytt

### ISSUE THREAD

**Issue by Petahhh** [vmware-tanzu/carvel-ytt#107]
In this example we see the 3 files `config.yml`, `funcs.lib.yml` and `funcs.star` formatted into the output on the right. https://get-ytt.io/#example:example-load

The terminal command to execute this is possibly:

```
ytt -f config.yml -f funcs.lib.yml -f funcs.star
```

If you broke out your yml into several files in subdirectories the same command can grow into something like this:

```
ytt -f config.yml -f funcs.lib.yml -f funcs.star -f other.lib.yml -f more/stuff.lib.yml -f even/more.lib.yml ... -f last.lib.yml
```

Is there a convenient way to say something along the lines of "format all the .lib.yml files here"? It would be really great if the following was possible:

```
ytt -f config.yml -f *.lib.yml
```

or 

```
ytt -f config.yml {,**}/*.lib.yml
```

**Comment by cppforlife** [comment]
> Is there a convenient way to say something along the lines of "format all the .lib.yml files here"?

not currently since shell globbing `*` would have to prepend `-f` to each file. we probably should add another flag or our own globbing for this.

given above, i typically recommend to group files into directories (e.g. `ytt -f config/` which includes all necessary files for ytt execution). as a side effect it hides individual files as impl details from end user running ytt.

**Comment by Petahhh** [comment]
Thanks @cppforlife !!

This `ytt -f config/`, is pretty convenient and I'm going to use it right away. Could this be recursive? If so, that would be great too.

**Comment by cppforlife** [comment]
> Could this be recursive?

it's recursive.

**Comment by pivotaljohn** [comment]
Looks like the original need was met with the advice given. In general, we don't have plans to add globbing to `ytt`'s scope. Let's open this back up if the question/need arises.
