### ISSUE TITLE
[overlay] reconsider ytt behaviour of overlaying map on top of nil

### ISSUE THREAD

**Issue by cppforlife** [vmware-tanzu/carvel-ytt#108]
currently overlay module will not allow to do so.

**Comment by pivotaljohn** [comment]
When a Configuration Author declares a map item in schema as `@schema/nullable`, its default value is `null`.
When a Configuration Consumer then provides a value for that item, that overlay hits this condition.

As far as I understand it, the hesitation for allowing this kind of operation is that it is not type safe: _anything_ can be placed over that null value. Kindly, subsequent type checks performed by schema more precisely address this concern.
