### ISSUE TITLE
Arbitrary precision integers and arithmetics

### ISSUE THREAD

**Issue by dynaxis** [vmware-tanzu/carvel-ytt#117]
It seems Starlark supports arbitrary precision integers. But I see precision loss in ytt after template processing for integers larger than `2 ** 63`, and more loss when output is in JSON, where I guess integers are converted to 64-bit floating point numbers before converted to JSON. Do you have any plan to support arbitrary precision integers in ytt? If not, will you accept a PR if someone issues one implementing the arbitrary precision integer support?

**Comment by cppforlife** [comment]
> Do you have any plan to support arbitrary precision integers in ytt?

as long as yaml/json is able to support this (which i think they do), i expect ytt to support it as well.

> If not, will you accept a PR if someone issues one implementing the arbitrary precision integer support?

PRs would be welcome.

**Comment by dynaxis** [comment]
@cppforlife actually I'm writing JSON schemas with ytt. Since I rely on regexp's a lot, it's quite handy to have a template language. As you said, YAML/JSON don't mandate such arbitrary precision but rather just permits implementations to set limits on range and precision at their own will (https://tools.ietf.org/html/rfc7159#section-6). So there is nothing to preclude such a support.

With you guys at least welcoming a PR, I'll try to investigate more on this issue for eventual submission of a PR. In case you have any plan set up for an implementation, please let me know. I'll be back when I have a sharable progress.

Thanks.

**Comment by cppforlife** [comment]
> So there is nothing to preclude such a support.

that makes sense. given that starlark supports it i think it makes to make sure that ytt supports it as well.

> With you guys at least welcoming a PR, I'll try to investigate more on this issue for eventual submission of a PR. In case you have any plan set up for an implementation, please let me know. I'll be back when I have a sharable progress.

👍, let us know how it goes.

**Comment by pivotaljohn** [comment]
Noting:
- there hasn't been movement on this for the year
- supporting arbitrary precision integers hasn't been — to date — a design goal

So, let's close this issue for now. If there's renewed interest, we can re-open. 👍🏼
