### ISSUE TITLE
Inform user about options when inputs include non-YAML files and not output flag given

### ISSUE THREAD

**Issue by pivotaljohn** [vmware-tanzu/carvel-ytt#132]
_edit: ⚠️ see [Cohen-style User Story format below](https://github.com/k14s/ytt/issues/132#issuecomment-725524292) ⚠️_

---

It's unclear from the result that when a user includes a non-YAML template and the destination is standard out, that its output is not included on purpose.

Let's give them a hint. For example, on stderr, we could say,
```
There are templates marked for output that are not included in this output.
Non-YAML templates are not rendered to standard output.
If you want to include those results, use the --output-directory flag.
```

---
cc: @pivotal-dean

**Comment by cppforlife** [comment]
mind providing more detailed example when this is the case?

**Comment by pivotaljohn** [comment]
A user is developing a text template (call it `app.ini`).

They run `ytt` with just that template:

```console
$ ytt -f app.ini.txt
$
```

They expected to see output, but see nothing.

They try again with `--debug`

```console
$ ytt -f app.ini.txt --debug
-  (private false)
  files:
  - app.ini.txt
  libraries:
    <none>
## file app.ini.txt
### template
src:  tmpl: code: | srccode
????:    1: __ytt_tpl2_set_ctx_type("text") |
????:    2: __ytt_tpl2_start_ctx("text") |
????:    3: __ytt_tpl2_start_node(1) |
   1:    4: __ytt_tpl2_start_node(2) |
   1:    5: __ytt_tpl2_set_node(2) |
   1:    6:  module="core"  |  module="core"
   1:    7: __ytt_tpl2_start_node(3) | [
   1:    8: __ytt_tpl2_set_node(3) | [
   2:    9: __ytt_tpl2_start_node(4) | =- module -
   2:   10: __ytt_tpl2_set_node(4, ( module )) | =- module -
   2:   11: __ytt_tpl2_start_node(5) | ]
  param1 = value

   2:   12: __ytt_tpl2_set_node(5) | ]
  param1 = value

????:   13: __ytt_tpl2_end_ctx() | ### app.ini.txt result
[core]
  param1 = value
### result
total: 439.781µs
```

and see that the template runs, but not included in the result.

**Comment by pivotaljohn** [comment]
**As a** Configuration Consumer (particularly someone who hasn't used `ytt` to render non-YAML files before),
**I want** to quickly (and in a kind way) learn how to specify where output should go
**So that** I don't waste time wondering why my non-YAML files didn't seem to render.

---

### Scenario: Library includes just non-YAML files and no output flag is specified
**Given** the enumerated input files include only non-YAML output files (e.g. `app.ini.txt`)
**When** `ytt` is invoked without any flag indicating location of output
```console
ytt -f app.ini.txt
```
**Then** I see a warning explaining that nothing will output without help from a flag.

__

### Scenario: Library includes a mix of YAML and non-YAML files and no output flag is specified
**Given** the enumerated input files includes some YAML files and some non-YAML files (e.g. `app.ini.txt` and `config.yml`)
**When** `ytt` is invoked without any flag indicating location of output (e.g. `--output-directory` or `--dangerous-emptied-output-directory`)
```console
ytt-f app.ini.txt -f config.yml
```
**Then** I see the YAML results on Standard In and a warning explaining that nothing will output without help from a flag on Standard Error

---
see also:
- https://github.com/k14s/ytt/blob/develop/docs/outputs.md
- https://github.com/k14s/ytt/blob/develop/docs/file-marks.md
 - https://github.com/k14s/ytt/blob/develop/docs/ytt-text-templating.md
