### ISSUE TITLE
unknown file location for nodes added via template.replace

### ISSUE THREAD

**Issue by cppforlife** [vmware-tanzu/carvel-ytt#151]
repro: https://get-ytt.io/#gist:https://gist.github.com/cppforlife/d83f925e9f02b605205afd95afdae29d

**Comment by pivotaljohn** [comment]
Q1: Is there any reason to not establish and maintain the invariant that the AST _always_ be a composite of `Node`?

Q2: what are the consequences of defining the "source line number" of such values to be the line where the `template.replace()` itself injects the new node(s)?

**Comment by pivotaljohn** [comment]
A little backlog grooming: the "discussion" was had in comments on #443.

We'll consider this issue addressed, for now. There remains the question of how feasible it is to more precisely identify the source of a given value when it originates from within Starlark execution. If that need arises, a separate issue can be created to capture it.
