### ISSUE TITLE
add --data-values-file-yaml to load data values from yaml files that do not have @data/values annotation

### ISSUE THREAD

**Issue by cppforlife** [vmware-tanzu/carvel-ytt#51]
currently following works

```
$ ytt --data-values-inspect -f values.yml=<(echo -e "#@data/values\n---\nstores: [1, 2, 3]")
stores:
- 1
- 2
- 3
```

however, it would be nice to have following work as well:

```
$ ytt --data-values-inspect --data-values-file-yaml <(echo "stores: [1, 2, 3]")
stores:
- 1
- 2
- 3
```

Related Conversations:
- https://kubernetes.slack.com/archives/CH8KCCKA5/p1567035583060800
- https://kubernetes.slack.com/archives/CH8KCCKA5/p1605718554315200

**Comment by cppforlife** [comment]
note to self: downside of this feature is that it becomes less friendly to library module inclusion since files wont be annotated as data/values.

**Comment by jtigger** [comment]
What if the file extension `.data` implied the `#@data/values` annotation?

```
ytt --data-values-inspect -f values.data.yml=<(echo -e "stores: [1, 2, 3]")
```

I think it also patches up the problem with libraries.

**Comment by pivotaljohn** [comment]
This was implemented as the `--data-values-file` and `library.with_data_values(plain=True)` features.

**Comment by jessehu** [comment]
Hi John, is there an example for this feature?
