### ISSUE TITLE
improve error message when files are on fs but were not specified via -f flags

### ISSUE THREAD

**Issue by cppforlife** [vmware-tanzu/carvel-ytt#9]
this would be an improvement to existing error messages to indicate why ytt isnt allowing to load a file that was not explicitly included via -f/-R flags. outcome of https://github.com/k14s/ytt/issues/7

**Comment by pivotaljohn** [comment]
Fixed in https://github.com/vmware-tanzu/carvel-ytt/commit/5ad452e517f31e504a33e7d825a69d24f33cb17c release in v0.27.0.
