### ISSUE TITLE
add intellij syntax highlighting for ytt

### ISSUE THREAD

**Issue by rnandi** [vmware-tanzu/carvel-ytt#97]

**Comment by cppforlife** [comment]
probably two things to consider here:
- highlighting yaml structure
- highlighting code (starlark) within #@
- highlighting comments (arbitrary text) within #!
- support for folding?

**Comment by gberche-orange** [comment]
Related backlog entry in intellij regarding Starlark support https://youtrack.jetbrains.com/issue/GO-7511/Support-for-Starlark-configuration-language

**Comment by pivotaljohn** [comment]
Given the range of editors that folks editing YAML are using, best to track this as #217.
